const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('git', {
  openRepo: () => ipcRenderer.invoke('open-repo'),
  loadRepos: () => ipcRenderer.invoke('load-repos'),
  saveRepos: (repos) => ipcRenderer.invoke('save-repos', repos),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  setWindowChrome: (c) => ipcRenderer.invoke('set-window-chrome', c),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  // Pushed, not asked for: macOS changes appearance on its own, and while the
  // window follows the OS the main process is the only side that can see it.
  onSystemTheme: (cb) => ipcRenderer.on('system-theme', (_, s) => cb(s)),
  status: (p) => ipcRenderer.invoke('git-status', p),
  log: (p, branch, limit, opts) => ipcRenderer.invoke('git-log', p, branch, limit, opts),
  branches: (p) => ipcRenderer.invoke('git-branches', p),
  unpushed: (p, ref, opts) => ipcRenderer.invoke('git-unpushed', p, ref, opts),
  repoState: (p) => ipcRenderer.invoke('git-repo-state', p),
  markResolved: (p, file) => ipcRenderer.invoke('git-mark-resolved', p, file),
  useOurs: (p, file) => ipcRenderer.invoke('git-use-ours', p, file),
  useTheirs: (p, file) => ipcRenderer.invoke('git-use-theirs', p, file),
  keepFile: (p, file) => ipcRenderer.invoke('git-keep-file', p, file),
  removeFile: (p, file) => ipcRenderer.invoke('git-remove-file', p, file),
  fileContents: (p, file) => ipcRenderer.invoke('git-file-contents', p, file),
  continueOperation: (p, kind) => ipcRenderer.invoke('git-continue-operation', p, kind),
  abortOperation: (p, kind) => ipcRenderer.invoke('git-abort-operation', p, kind),
  repoFingerprint: (p) => ipcRenderer.invoke('git-repo-fingerprint', p),
  isRepo: (p) => ipcRenderer.invoke('git-is-repo', p),
  accessProblem: (p) => ipcRenderer.invoke('git-access-problem', p),
  tags: (p) => ipcRenderer.invoke('git-tags', p),
  remotes: (p) => ipcRenderer.invoke('git-remotes', p),
  stashes: (p) => ipcRenderer.invoke('git-stashes', p),
  diff: (p, file, staged) => ipcRenderer.invoke('git-diff', p, file, staged),
  untrackedDiff: (p, file) => ipcRenderer.invoke('git-untracked-diff', p, file),
  commitDetail: (p, hash) => ipcRenderer.invoke('git-commit-detail', p, hash),
  commitDiff: (p, hash) => ipcRenderer.invoke('git-commit-diff', p, hash),
  commitFiles: (p, hash) => ipcRenderer.invoke('git-commit-files', p, hash),
  commitFileDiff: (p, hash, file) => ipcRenderer.invoke('git-commit-file-diff', p, hash, file),
  rangeFiles: (p, base, head) => ipcRenderer.invoke('git-range-files', p, base, head),
  rangeFileDiff: (p, base, head, file) => ipcRenderer.invoke('git-range-file-diff', p, base, head, file),
  rangeCommits: (p, base, head) => ipcRenderer.invoke('git-range-commits', p, base, head),
  fetchPullRequest: (p, remote, number) => ipcRenderer.invoke('git-fetch-pr', p, remote, number),
  pullRequests: (p, forge) => ipcRenderer.invoke('forge-pulls', p, forge),
  reviewComments: (p, forge, number) => ipcRenderer.invoke('forge-review-comments', p, forge, number),
  submitReview: (p, forge, review) => ipcRenderer.invoke('forge-submit-review', p, forge, review),
  react: (p, forge, opts) => ipcRenderer.invoke('forge-react', p, forge, opts),
  reactions: (p, forge, target) => ipcRenderer.invoke('forge-reactions', p, forge, target),
  viewerLogin: (p, forge) => ipcRenderer.invoke('forge-viewer', p, forge),
  workflowRun: (p, forge, target) => ipcRenderer.invoke('forge-workflow-run', p, forge, target),
  searchLog: (p, query, field, branch, limit, opts) => ipcRenderer.invoke('git-search-log', p, query, field, branch, limit, opts),
  stage: (p, file) => ipcRenderer.invoke('git-stage', p, file),
  unstage: (p, file, oldPath) => ipcRenderer.invoke('git-unstage', p, file, oldPath),
  stageAll: (p) => ipcRenderer.invoke('git-stage-all', p),
  commit: (p, msg, opts) => ipcRenderer.invoke('git-commit', p, msg, opts),
  headMessage: (p) => ipcRenderer.invoke('git-head-message', p),
  checkout: (p, branch) => ipcRenderer.invoke('git-checkout', p, branch),
  createBranch: (p, name, from) => ipcRenderer.invoke('git-create-branch', p, name, from),
  deleteBranch: (p, name) => ipcRenderer.invoke('git-delete-branch', p, name),
  renameBranch: (p, oldN, newN) => ipcRenderer.invoke('git-rename-branch', p, oldN, newN),
  merge: (p, branch) => ipcRenderer.invoke('git-merge', p, branch),
  rebase: (p, branch) => ipcRenderer.invoke('git-rebase', p, branch),
  pull: (p) => ipcRenderer.invoke('git-pull', p),
  push: (p, opts) => ipcRenderer.invoke('git-push', p, opts),
  fetch: (p) => ipcRenderer.invoke('git-fetch', p),
  fetchQuiet: (p) => ipcRenderer.invoke('git-fetch-quiet', p),
  stashSave: (p, msg) => ipcRenderer.invoke('git-stash-save', p, msg),
  stashApply: (p, idx) => ipcRenderer.invoke('git-stash-apply', p, idx),
  stashDrop: (p, idx) => ipcRenderer.invoke('git-stash-drop', p, idx),
  revert: (p, hash) => ipcRenderer.invoke('git-revert', p, hash),
  cherryPick: (p, hash) => ipcRenderer.invoke('git-cherry-pick', p, hash),
  createTag: (p, name, ref) => ipcRenderer.invoke('git-create-tag', p, name, ref),
  deleteTag: (p, name) => ipcRenderer.invoke('git-delete-tag', p, name),
  stageHunk: (p, file, hunk, index) => ipcRenderer.invoke('git-stage-hunk', p, file, hunk, index),
  discardHunk: (p, file, hunk, index) => ipcRenderer.invoke('git-discard-hunk', p, file, hunk, index),
  discardFile: (p, file) => ipcRenderer.invoke('git-discard-file', p, file),
  trashFile: (p, file) => ipcRenderer.invoke('git-trash-file', p, file),
  showInFinder: (p, file) => ipcRenderer.invoke('git-show-in-finder', p, file),
});

// Releasing is its own bridge for the same reason updates are: nothing here
// speaks git, and the output arrives in pieces while the command runs rather
// than as the return value of a call.
contextBridge.exposeInMainWorld('release', {
  inspect: (p) => ipcRenderer.invoke('release-inspect', p),
  run: (p, command) => ipcRenderer.invoke('release-run', p, command),
  cancel: () => ipcRenderer.invoke('release-cancel'),
  onOutput: (cb) => ipcRenderer.on('release-output', (_, chunk) => cb(chunk)),
});

// Updates are their own bridge rather than another key on `git` — nothing here
// touches a repository, and onState pushes from main instead of being called.
contextBridge.exposeInMainWorld('updates', {
  state: () => ipcRenderer.invoke('update-state'),
  check: () => ipcRenderer.invoke('update-check'),
  install: () => ipcRenderer.invoke('update-install'),
  onState: (cb) => ipcRenderer.on('update-state', (_, s) => cb(s)),
});
